export type RepertoireCategory = "filosofia" | "dados" | "literatura" | "historia" | "ciencia" | "arte" | "legislacao";

export type RepertoireTheme =
  | "tecnologia" | "desigualdade" | "educacao" | "saude" | "meio-ambiente"
  | "democracia" | "genero" | "racismo" | "violencia" | "trabalho" | "cultura";

export interface Repertoire {
  id: string;
  author: string;
  work?: string;
  quote?: string;
  summary: string;
  category: RepertoireCategory;
  themes: RepertoireTheme[];
  howToUse: string;
  example: string;
  tags: string[];
}

export const repertoires: Repertoire[] = [
  // ── FILOSOFIA ──
  {
    id: "r1",
    author: "Hannah Arendt",
    work: "A Condição Humana (1958)",
    quote: "A banalidade do mal",
    summary: "Arendt analisa como sistemas autoritários transformam pessoas comuns em perpetradoras de atrocidades por omissão do pensamento crítico. Também teoriza o espaço público como condição para a vida política plena.",
    category: "filosofia",
    themes: ["democracia", "violencia", "tecnologia"],
    howToUse: "Use para argumentar sobre manipulação política, fake news, alienação digital ou qualquer tema que envolva a deterioração do pensamento crítico e do espaço público.",
    example: "Conforme Hannah Arendt teoriza em 'A Condição Humana', a democracia pressupõe um espaço público de deliberação racional — espaço esse que os algoritmos das redes sociais fragmentam ao criar câmaras de eco que eliminam o dissenso.",
    tags: ["espaço público", "pensamento crítico", "totalitarismo", "política"],
  },
  {
    id: "r2",
    author: "Zygmunt Bauman",
    work: "Modernidade Líquida (2000)",
    summary: "Bauman descreve a contemporaneidade como 'líquida': relações, identidades e instituições perdem solidez e tornam-se fluidas, provisórias e instáveis. O consumismo e a individualização fragmentam os laços sociais.",
    category: "filosofia",
    themes: ["tecnologia", "cultura", "trabalho", "desigualdade"],
    howToUse: "Excelente para temas sobre identidade digital, vínculos afetivos fragilizados, consumismo, trabalho precário e qualquer contexto de instabilidade social contemporânea.",
    example: "O sociólogo Zygmunt Bauman, ao cunhar o conceito de 'modernidade líquida', antecipou que as identidades contemporâneas tornar-se-iam maleáveis e vulneráveis à manipulação — fenômeno agravado pelo uso de dados pessoais pelas plataformas digitais.",
    tags: ["modernidade líquida", "identidade", "consumismo", "vínculos sociais"],
  },
  {
    id: "r3",
    author: "Simone de Beauvoir",
    work: "O Segundo Sexo (1949)",
    quote: "Ninguém nasce mulher, torna-se mulher.",
    summary: "Beauvoir demonstra que o feminino é uma construção social e cultural, não uma essência natural. A opressão da mulher é resultado de um processo histórico de subordinação que naturaliza a desigualdade.",
    category: "filosofia",
    themes: ["genero", "violencia", "trabalho", "desigualdade"],
    howToUse: "Indispensável para temas sobre violência de gênero, desigualdade salarial, invisibilidade do trabalho feminino ou qualquer discussão sobre construção social de papéis.",
    example: "Conforme Simone de Beauvoir expõe em 'O Segundo Sexo', a subordinação feminina não é natural — ela é construída culturalmente, o que explica por que a violência contra a mulher persiste mesmo após décadas de legislação protetiva.",
    tags: ["feminismo", "gênero", "construção social", "patriarcado"],
  },
  {
    id: "r4",
    author: "Michel Foucault",
    work: "Vigiar e Punir (1975)",
    summary: "Foucault analisa como o poder disciplinar moderno opera por meio de vigilância, normalização e controle dos corpos, criando sujeitos dóceis e produtivos. O Panóptico é sua metáfora central.",
    category: "filosofia",
    themes: ["tecnologia", "democracia", "violencia", "saude"],
    howToUse: "Use para temas sobre vigilância digital, controle social, sistemas prisionais, medicalização ou qualquer contexto que envolva poder e controle sobre corpos e comportamentos.",
    example: "Michel Foucault, ao analisar o Panóptico em 'Vigiar e Punir', demonstrou que a vigilância constante transforma o vigiado em seu próprio controlador — princípio que os algoritmos de redes sociais reproduzem ao monitorar e moldar comportamentos digitais.",
    tags: ["vigilância", "poder", "panóptico", "controle social"],
  },
  {
    id: "r5",
    author: "Byung-Chul Han",
    work: "Sociedade do Cansaço (2010)",
    summary: "Han argumenta que a sociedade contemporânea substituiu a disciplina coercitiva pelo desempenho autoimposto, gerando esgotamento, depressão e burnout como doenças do século XXI.",
    category: "filosofia",
    themes: ["saude", "trabalho", "tecnologia", "cultura"],
    howToUse: "Perfeito para temas sobre saúde mental, burnout, produtividade excessiva, redes sociais e cultura do desempenho. Um dos repertórios mais atuais e reconhecidos pelos avaliadores.",
    example: "O filósofo Byung-Chul Han, em 'Sociedade do Cansaço', diagnostica que o imperativo do desempenho — amplificado pelas redes sociais — transforma o indivíduo em explorador de si mesmo, gerando uma epidemia silenciosa de esgotamento e ansiedade.",
    tags: ["burnout", "desempenho", "saúde mental", "produtividade"],
  },
  {
    id: "r6",
    author: "Boaventura de Sousa Santos",
    work: "Epistemologias do Sul (2010)",
    summary: "Santos propõe que o conhecimento ocidental suprimiu saberes de povos do Sul Global — fenômeno que chama de 'epistemicídio'. Defende a valorização de formas alternativas de saber.",
    category: "filosofia",
    themes: ["racismo", "educacao", "desigualdade", "cultura"],
    howToUse: "Use para temas sobre povos indígenas, quilombolas, desigualdade epistêmica, educação inclusiva ou qualquer contexto que envolva invisibilidade de grupos subalternizados.",
    example: "Boaventura de Sousa Santos, ao cunhar o conceito de 'epistemicídio', revela que a exclusão dos povos indígenas não se limita ao plano econômico — ela atinge também o silenciamento de seus saberes e cosmologias, perpetuando sua invisibilidade institucional.",
    tags: ["epistemicídio", "povos indígenas", "conhecimento", "colonialismo"],
  },
  {
    id: "r7",
    author: "Pierre Bourdieu",
    work: "A Reprodução (1970)",
    summary: "Bourdieu demonstra que o sistema educacional não neutraliza desigualdades sociais — ele as reproduz, ao privilegiar o capital cultural das classes dominantes e tratar como 'natural' o que é socialmente construído.",
    category: "filosofia",
    themes: ["educacao", "desigualdade", "racismo", "trabalho"],
    howToUse: "Essencial para temas sobre desigualdade educacional, evasão escolar, acesso ao ensino superior ou qualquer discussão sobre meritocracia e reprodução social.",
    example: "Pierre Bourdieu, em 'A Reprodução', demonstra que a escola não é um espaço neutro: ao valorizar o capital cultural das elites, ela legitima a desigualdade como mérito individual, perpetuando ciclos de exclusão que afetam desproporcionalmente negros e pobres.",
    tags: ["capital cultural", "reprodução social", "meritocracia", "escola"],
  },

  // ── DADOS E ESTATÍSTICAS ──
  {
    id: "r8",
    author: "IBGE",
    work: "Pesquisa Nacional por Amostra de Domicílios (PNAD) 2023",
    summary: "O IBGE é o principal órgão de estatística do Brasil. A PNAD mede indicadores como renda, emprego, educação e desigualdade. O coeficiente de Gini do Brasil é de 0,518 — um dos mais altos do mundo.",
    category: "dados",
    themes: ["desigualdade", "trabalho", "educacao", "saude", "racismo"],
    howToUse: "Cite o IBGE para dar credibilidade empírica a argumentos sobre desigualdade, pobreza, educação ou trabalho. Sempre especifique o indicador e o ano.",
    example: "Segundo dados do IBGE (PNAD 2023), o Brasil possui um coeficiente de Gini de 0,518, evidenciando que a concentração de renda permanece entre as mais elevadas do mundo — realidade que alimenta ciclos de exclusão social e limita a mobilidade econômica.",
    tags: ["desigualdade", "renda", "GINI", "pobreza"],
  },
  {
    id: "r9",
    author: "OMS — Organização Mundial da Saúde",
    work: "Relatório Mundial de Saúde Mental (2022)",
    summary: "A OMS estima que 1 bilhão de pessoas vivem com algum transtorno mental no mundo. No Brasil, a depressão afeta 11,5 milhões de pessoas (5,8% da população), a maior taxa da América Latina.",
    category: "dados",
    themes: ["saude", "tecnologia", "trabalho", "desigualdade"],
    howToUse: "Use para temas sobre saúde mental, burnout, redes sociais e bem-estar. A OMS é a fonte de maior autoridade internacional em saúde.",
    example: "Conforme dados da Organização Mundial da Saúde (2022), a depressão afeta 11,5 milhões de brasileiros — números que evidenciam uma crise de saúde pública amplificada pelo uso compulsivo de plataformas digitais e pela cultura do desempenho.",
    tags: ["depressão", "saúde mental", "transtorno", "bem-estar"],
  },
  {
    id: "r10",
    author: "Instituto Reuters",
    work: "Digital News Report 2023",
    summary: "Relatório anual sobre consumo de notícias. Aponta que 64% dos brasileiros já foram expostos a notícias falsas e que o Brasil é um dos países com maior desconfiança em relação à mídia tradicional.",
    category: "dados",
    themes: ["tecnologia", "democracia", "educacao"],
    howToUse: "Use para temas sobre desinformação, fake news, democracia digital ou qualquer discussão sobre o papel da mídia na sociedade.",
    example: "Segundo o Instituto Reuters (Digital News Report, 2023), 64% dos brasileiros já foram expostos a informações falsas que influenciaram sua percepção de eventos políticos, revelando a dimensão da crise de desinformação que corrói as bases da democracia representativa.",
    tags: ["fake news", "desinformação", "mídia", "democracia"],
  },
  {
    id: "r11",
    author: "Fórum Brasileiro de Segurança Pública",
    work: "Anuário de Segurança Pública 2023",
    summary: "O Brasil registrou 1.463 casos de feminicídio em 2022 — um a cada 6 horas. Mulheres negras representam 61,8% das vítimas, revelando a intersecção entre gênero e racismo.",
    category: "dados",
    themes: ["genero", "violencia", "racismo", "desigualdade"],
    howToUse: "Use para temas sobre violência de gênero, feminicídio ou interseccionalidade racial. Dado concreto e recente que tem alto impacto nos avaliadores.",
    example: "Dados do Fórum Brasileiro de Segurança Pública (2023) revelam que o Brasil registra um feminicídio a cada 6 horas, com mulheres negras representando 61,8% das vítimas — número que expõe a intersecção estrutural entre patriarcado e racismo.",
    tags: ["feminicídio", "violência de gênero", "racismo", "mulheres negras"],
  },
  {
    id: "r12",
    author: "UNESCO",
    work: "Relatório de Monitoramento Global da Educação 2023",
    summary: "A UNESCO estima que 244 milhões de crianças e jovens estão fora da escola no mundo. No Brasil, a evasão escolar atinge 1,7 milhão de jovens entre 15 e 17 anos.",
    category: "dados",
    themes: ["educacao", "desigualdade", "trabalho"],
    howToUse: "Use para temas sobre educação, evasão escolar ou qualquer argumento que demande autoridade internacional em educação.",
    example: "Segundo a UNESCO (2023), 1,7 milhão de jovens brasileiros entre 15 e 17 anos estão fora da escola — realidade que compromete não apenas o desenvolvimento individual, mas a capacidade produtiva e democrática do país.",
    tags: ["evasão escolar", "educação básica", "jovens", "exclusão"],
  },

  // ── LITERATURA E OBRAS ──
  {
    id: "r13",
    author: "George Orwell",
    work: "1984 (1949)",
    summary: "Distopia em que um Estado totalitário controla o pensamento por meio da vigilância permanente (Grande Irmão), da manipulação da linguagem (Novilíngua) e da reescrita da história.",
    category: "literatura",
    themes: ["tecnologia", "democracia", "violencia"],
    howToUse: "Use para temas sobre vigilância digital, autoritarismo, liberdade de expressão ou manipulação de informações. Um dos repertórios mais reconhecidos pelos avaliadores.",
    example: "George Orwell, em '1984', antecipou que a vigilância permanente não precisaria de força física para subjugar — bastaria a consciência de ser observado para que o indivíduo se autocensurasse, dinâmica que os algoritmos contemporâneos reproduzem com precisão.",
    tags: ["vigilância", "totalitarismo", "liberdade", "dystopia"],
  },
  {
    id: "r14",
    author: "Chimamanda Ngozi Adichie",
    work: "O Perigo de Uma Única História (TED, 2009)",
    quote: "A única história cria estereótipos, e o problema com estereótipos não é que sejam mentira, mas que são incompletos.",
    summary: "Adichie argumenta que quando conhecemos apenas uma narrativa sobre um povo ou lugar, criamos estereótipos que distorcem a realidade e perpetuam preconceitos.",
    category: "literatura",
    themes: ["racismo", "cultura", "educacao", "genero"],
    howToUse: "Excelente para temas sobre racismo, representatividade, mídia e estereótipos. A frase é marcante e memorável para os avaliadores.",
    example: "A escritora nigeriana Chimamanda Ngozi Adichie alerta que 'a única história cria estereótipos', fenômeno que explica como a sub-representação de negros nos meios de comunicação brasileiros perpetua preconceitos e limita o sentimento de pertencimento dessa população.",
    tags: ["estereótipos", "representatividade", "narrativa", "preconceito"],
  },
  {
    id: "r15",
    author: "Conceição Evaristo",
    work: "Becos da Memória (2006) / Escrevivência",
    summary: "Evaristo cunhou o conceito de 'escrevivência' — a escrita a partir da vivência de mulheres negras que foram historicamente silenciadas — tornando-se referência essencial em literatura afro-brasileira.",
    category: "literatura",
    themes: ["racismo", "genero", "cultura", "educacao"],
    howToUse: "Use para temas sobre racismo, feminismo negro, invisibilidade cultural ou literatura brasileira. Valorizada nos contextos em que o candidato demonstra conhecimento da cultura nacional.",
    example: "A escritora Conceição Evaristo, ao criar o conceito de 'escrevivência', evidencia que a literatura pode ser instrumento de resistência para grupos historicamente silenciados — resposta estética e política à invisibilidade imposta às mulheres negras na sociedade brasileira.",
    tags: ["escrevivência", "mulheres negras", "literatura afro-brasileira", "resistência"],
  },

  // ── HISTÓRIA E EVENTOS ──
  {
    id: "r16",
    author: "Cambridge Analytica",
    work: "Escândalo de dados (2018)",
    summary: "A empresa coletou dados de 87 milhões de usuários do Facebook sem consentimento e os usou para microssegmentar propaganda política, influenciando as eleições americanas de 2016 e o Brexit.",
    category: "historia",
    themes: ["tecnologia", "democracia"],
    howToUse: "Caso histórico concreto e verificável para temas sobre privacidade de dados, manipulação política digital ou regulação de plataformas.",
    example: "O escândalo Cambridge Analytica (2018), no qual dados de 87 milhões de usuários foram explorados para influenciar eleições em múltiplos países, demonstra como a ausência de regulação de dados pessoais pode comprometer a soberania democrática.",
    tags: ["dados pessoais", "eleições", "Facebook", "manipulação política"],
  },
  {
    id: "r17",
    author: "Lei Maria da Penha",
    work: "Lei 11.340/2006",
    summary: "Criada após a história de Maria da Penha Maia Fernandes, que sofreu tentativas de homicídio por seu marido, a lei estabelece mecanismos de proteção para mulheres vítimas de violência doméstica.",
    category: "legislacao",
    themes: ["genero", "violencia", "democracia"],
    howToUse: "Use como evidência de que o Brasil possui legislação protetiva, mas que sua aplicação ainda é insuficiente — criando tensão argumentativa entre lei e realidade.",
    example: "A Lei Maria da Penha (11.340/2006), considerada pela ONU uma das três melhores legislações de combate à violência doméstica no mundo, demonstra que o Brasil possui arcabouço legal adequado — o desafio reside em sua efetiva implementação e na capacitação dos agentes que a aplicam.",
    tags: ["violência doméstica", "proteção", "direitos humanos", "legislação"],
  },
  {
    id: "r18",
    author: "Movimento Quilombola",
    work: "Artigo 68 do ADCT — Constituição Federal de 1988",
    summary: "A Constituição de 1988 garantiu às comunidades quilombolas o direito à propriedade definitiva de suas terras. Porém, décadas depois, menos de 15% dos territórios foram titulados.",
    category: "historia",
    themes: ["racismo", "desigualdade", "democracia"],
    howToUse: "Use para temas sobre racismo estrutural, direitos constitucionais não efetivados ou desigualdade fundiária. Demonstra distância entre lei e realidade.",
    example: "Embora o Artigo 68 do ADCT da Constituição Federal (1988) reconheça o direito das comunidades quilombolas à titulação de suas terras, mais de três décadas depois, menos de 15% desses territórios foram efetivamente regularizados — evidência concreta do racismo estrutural que permeia as instituições brasileiras.",
    tags: ["quilombolas", "terra", "racismo estrutural", "Constituição"],
  },

  // ── FILOSOFIA (continuação) ──
  {
    id: "r21",
    author: "Paulo Freire",
    work: "Pedagogia do Oprimido (1968)",
    quote: "Ninguém educa ninguém, ninguém educa a si mesmo, os homens se educam entre si, mediatizados pelo mundo.",
    summary: "Freire critica a 'educação bancária' — modelo em que o aluno é receptáculo passivo — e propõe educação dialógica e libertadora, que parte da realidade do educando para transformar o mundo.",
    category: "filosofia",
    themes: ["educacao", "desigualdade", "democracia", "racismo"],
    howToUse: "Essencial para temas sobre educação pública, evasão escolar, analfabetismo ou qualquer contexto que envolva exclusão educacional e transformação social.",
    example: "Paulo Freire, ao denunciar a 'educação bancária' em 'Pedagogia do Oprimido', demonstrou que um sistema que ignora a realidade do educando não liberta — oprime. Essa lógica explica por que escolas periféricas, sem conexão com as vivências dos alunos, apresentam os maiores índices de evasão.",
    tags: ["educação bancária", "dialogicidade", "opressão", "libertação"],
  },
  {
    id: "r22",
    author: "Karl Marx",
    work: "O Capital (1867) / Manifesto Comunista (1848)",
    summary: "Marx analisa o capitalismo como sistema de exploração baseado na extração da mais-valia do trabalhador. Propõe que as contradições do capital levam inevitavelmente a conflitos de classe.",
    category: "filosofia",
    themes: ["trabalho", "desigualdade", "democracia"],
    howToUse: "Use para temas sobre desigualdade econômica, precarização do trabalho, concentração de renda ou qualquer discussão sobre relações entre capital e trabalho.",
    example: "Karl Marx, em 'O Capital', demonstrou que a concentração de riqueza não é acidente — é estrutura: o sistema capitalista depende da extração de excedente do trabalho, o que explica por que o crescimento econômico brasileiro historicamente não se traduz em redução da desigualdade.",
    tags: ["mais-valia", "capitalismo", "classe social", "exploração"],
  },
  {
    id: "r23",
    author: "Immanuel Kant",
    work: "Fundamentação da Metafísica dos Costumes (1785)",
    quote: "Age de tal forma que uses a humanidade, tanto na tua pessoa como na pessoa de qualquer outro, sempre como meio e nunca somente como fim.",
    summary: "Kant formula o Imperativo Categórico: princípio moral universal segundo o qual cada pessoa deve ser tratada como fim em si mesma, nunca como mero instrumento.",
    category: "filosofia",
    themes: ["democracia", "violencia", "genero", "tecnologia"],
    howToUse: "Use para temas que envolvam dignidade humana, exploração, violência ou qualquer situação em que pessoas são instrumentalizadas.",
    example: "O Imperativo Categórico de Immanuel Kant — que exige tratar todo ser humano como fim em si mesmo — é flagrantemente violado quando algoritmos comerciais monetizam dados pessoais sem consentimento, reduzindo o cidadão a produto.",
    tags: ["imperativo categórico", "dignidade", "ética", "moral"],
  },
  {
    id: "r24",
    author: "John Rawls",
    work: "Uma Teoria da Justiça (1971)",
    summary: "Rawls propõe o 'véu da ignorância': princípio segundo o qual uma sociedade justa seria aquela que escolheríamos se não soubéssemos qual posição nela ocuparíamos. Fundamenta políticas redistributivas e ações afirmativas.",
    category: "filosofia",
    themes: ["desigualdade", "educacao", "racismo", "democracia"],
    howToUse: "Excelente para defender cotas raciais, políticas de redistribuição ou qualquer medida de justiça social. O 'véu da ignorância' é um argumento de forte apelo racional.",
    example: "John Rawls, ao propor o 'véu da ignorância' em 'Uma Teoria da Justiça', fornece o fundamento filosófico para políticas de ação afirmativa: numa sociedade justa, escolheríamos regras que protegessem os mais vulneráveis, pois não saberíamos em qual posição nos encontraríamos.",
    tags: ["véu da ignorância", "justiça distributiva", "ação afirmativa", "equidade"],
  },
  {
    id: "r25",
    author: "Antonio Gramsci",
    work: "Cadernos do Cárcere (1929-1935)",
    summary: "Gramsci desenvolve o conceito de hegemonia cultural: o poder das classes dominantes se mantém não apenas pela força, mas pelo consenso — pela naturalização de valores, ideias e normas que legitimam a ordem social.",
    category: "filosofia",
    themes: ["democracia", "racismo", "cultura", "educacao", "genero"],
    howToUse: "Use para temas sobre naturalização de desigualdades, mídia, ideologia ou qualquer discussão sobre como o poder se perpetua pelo consenso cultural.",
    example: "O conceito gramsciano de hegemonia cultural explica por que práticas discriminatórias persistem mesmo sem força explícita: quando os valores da classe dominante são apresentados como 'naturais' e 'universais', a opressão é interiorizada e reproduzida pelos próprios oprimidos.",
    tags: ["hegemonia", "consenso", "ideologia", "cultura dominante"],
  },
  {
    id: "r26",
    author: "Frantz Fanon",
    work: "Os Condenados da Terra (1961)",
    summary: "Fanon analisa os efeitos psicológicos e sociais do colonialismo sobre os colonizados, demonstrando que a descolonização exige não apenas independência política, mas reconstrução da identidade e da subjetividade.",
    category: "filosofia",
    themes: ["racismo", "desigualdade", "cultura", "violencia"],
    howToUse: "Essencial para temas sobre racismo estrutural, colonialismo, identidade negra ou indígena e qualquer discussão sobre heranças do processo colonial.",
    example: "Frantz Fanon, em 'Os Condenados da Terra', demonstrou que o colonialismo não deixa apenas cicatrizes materiais — ele destrói a subjetividade do colonizado, processo que explica por que a superação do racismo estrutural brasileiro demanda políticas que vão além da reparação econômica.",
    tags: ["colonialismo", "descolonização", "identidade negra", "subjetividade"],
  },
  {
    id: "r27",
    author: "Émile Durkheim",
    work: "O Suicídio (1897) / As Regras do Método Sociológico (1895)",
    summary: "Durkheim demonstrou que fenômenos individuais como o suicídio são determinados por fatores sociais (integração e regulação social). Fundou a sociologia como ciência autônoma ao definir os 'fatos sociais'.",
    category: "filosofia",
    themes: ["saude", "trabalho", "cultura", "desigualdade"],
    howToUse: "Use para temas sobre saúde mental, suicídio, anomia social ou qualquer contexto em que comportamentos individuais revelam falhas coletivas.",
    example: "Émile Durkheim, em 'O Suicídio', demonstrou que a taxa de suicídios varia conforme o grau de integração social — dado que ressoa na contemporaneidade: o isolamento promovido pelas redes sociais pode ser fator de risco para transtornos mentais, não a causa única.",
    tags: ["anomia", "fatos sociais", "integração social", "suicídio"],
  },
  {
    id: "r28",
    author: "Amartya Sen",
    work: "Desenvolvimento como Liberdade (1999)",
    summary: "Sen redefine desenvolvimento não como crescimento do PIB, mas como expansão das liberdades reais dos indivíduos: acesso à educação, saúde, participação política e segurança econômica.",
    category: "filosofia",
    themes: ["desigualdade", "educacao", "saude", "democracia"],
    howToUse: "Use para argumentar que indicadores econômicos não refletem bem-estar real, ou para defender políticas sociais com base no conceito de 'capacitações'.",
    example: "Amartya Sen, ao redefine desenvolvimento como 'expansão de liberdades substantivas', evidencia que o crescimento do PIB brasileiro nas últimas décadas foi insuficiente: sem acesso universal à educação de qualidade e saúde, a maioria da população permanece privada das condições mínimas de liberdade real.",
    tags: ["desenvolvimento humano", "capacitações", "liberdades", "IDH"],
  },
  {
    id: "r29",
    author: "Herbert Marcuse",
    work: "O Homem Unidimensional (1964)",
    summary: "Marcuse argumenta que a sociedade industrial avançada cria 'falsas necessidades' que integram os indivíduos ao sistema, eliminando a capacidade crítica e a oposição verdadeira ao status quo.",
    category: "filosofia",
    themes: ["tecnologia", "cultura", "trabalho", "democracia"],
    howToUse: "Use para temas sobre consumismo, alienação digital, cultura de massa ou qualquer discussão sobre como a indústria cultural neutraliza o pensamento crítico.",
    example: "Herbert Marcuse, em 'O Homem Unidimensional', antecipou que a criação de 'falsas necessidades' pelo consumismo integraria os sujeitos ao sistema — lógica que as plataformas digitais aperfeiçoaram ao transformar engajamento em mercadoria e dependência em norma.",
    tags: ["falsas necessidades", "consumismo", "alienação", "indústria cultural"],
  },
  {
    id: "r30",
    author: "bell hooks",
    work: "Ensinando a Transgredir (1994) / O Feminismo é para Todo Mundo (2000)",
    summary: "A pensadora negra americana articula raça, gênero e classe como sistemas de opressão interligados (interseccionalidade), propondo uma pedagogia engajada que reconhece as experiências marginalizadas.",
    category: "filosofia",
    themes: ["genero", "racismo", "educacao", "desigualdade"],
    howToUse: "Use para temas que envolvam interseccionalidade, educação inclusiva, feminismo negro ou qualquer contexto em que raça, gênero e classe se sobrepõem.",
    example: "A filósofa bell hooks, ao articular raça, gênero e classe como sistemas entrelaçados de opressão, fornece o instrumental teórico para compreender por que mulheres negras acumulam desvantagens que superam a simples soma do racismo e do sexismo.",
    tags: ["interseccionalidade", "feminismo negro", "raça", "classe"],
  },

  // ── DADOS (continuação) ──
  {
    id: "r31",
    author: "PNUD — Programa das Nações Unidas para o Desenvolvimento",
    work: "Índice de Desenvolvimento Humano (IDH) 2023",
    summary: "O Brasil ocupa a 87ª posição no IDH global (0,754), classificado como 'alto desenvolvimento', mas com enorme desigualdade interna: o IDH dos 20% mais pobres equivale ao de países de baixo desenvolvimento.",
    category: "dados",
    themes: ["desigualdade", "educacao", "saude", "democracia"],
    howToUse: "Use para demonstrar que indicadores agregados mascaram desigualdades internas severas — o IDH médio do Brasil esconde um país com dois desenvolvimentos diferentes.",
    example: "Embora o PNUD classifique o Brasil como país de 'alto desenvolvimento humano' (IDH 0,754, 2023), essa média oculta uma fratura social profunda: o IDH dos 20% mais pobres equivale ao de países africanos, revelando que o desenvolvimento brasileiro é geograficamente e racialmente seletivo.",
    tags: ["IDH", "desenvolvimento humano", "desigualdade", "PNUD"],
  },
  {
    id: "r32",
    author: "CETIC.br — Centro Regional de Estudos para o Desenvolvimento da Sociedade da Informação",
    work: "TIC Domicílios 2023",
    summary: "Pesquisa aponta que 84% dos domicílios brasileiros têm acesso à internet, mas a qualidade e velocidade variam enormemente: populações rurais e de baixa renda acessam predominantemente via celular, com planos de dados limitados.",
    category: "dados",
    themes: ["tecnologia", "desigualdade", "educacao"],
    howToUse: "Use para argumentar que acesso à internet no Brasil é desigual, contrapondo-se à narrativa de 'inclusão digital' superficial.",
    example: "Segundo o CETIC.br (2023), apesar de 84% dos domicílios terem acesso à internet, a exclusão digital persiste em outra dimensão: populações de baixa renda acessam a rede predominantemente por celular com dados limitados, o que inviabiliza o uso para educação e trabalho remoto.",
    tags: ["exclusão digital", "acesso à internet", "desigualdade digital", "celular"],
  },
  {
    id: "r33",
    author: "IPEA — Instituto de Pesquisa Econômica Aplicada",
    work: "Atlas da Violência 2023",
    summary: "O Brasil registrou 47.508 homicídios em 2021. Jovens negros de 15 a 29 anos são as maiores vítimas: um jovem negro tem 2,9 vezes mais chance de ser assassinado do que um jovem branco.",
    category: "dados",
    themes: ["violencia", "racismo", "desigualdade"],
    howToUse: "Dado de alto impacto para temas sobre segurança pública, racismo estrutural ou desigualdade racial. A razão de chances é um argumento estatístico poderoso.",
    example: "O Atlas da Violência do IPEA (2023) revela que jovens negros brasileiros possuem 2,9 vezes mais chance de serem assassinados do que jovens brancos — estatística que expõe o racismo não como fenômeno individual, mas como estrutura letal que determina quem morre no Brasil.",
    tags: ["homicídio", "jovens negros", "racismo", "segurança pública"],
  },
  {
    id: "r34",
    author: "ONU Mulheres",
    work: "Relatório de Igualdade de Gênero 2023",
    summary: "No Brasil, mulheres ganham em média 77,7% do salário dos homens para funções equivalentes. A desigualdade aumenta quando se considera raça: mulheres negras ganham apenas 44% do salário de homens brancos.",
    category: "dados",
    themes: ["genero", "racismo", "trabalho", "desigualdade"],
    howToUse: "Use para temas sobre desigualdade salarial de gênero ou interseccionalidade racial. Os números tornam o argumento concreto e difícil de refutar.",
    example: "Segundo a ONU Mulheres (2023), mulheres negras no Brasil recebem apenas 44% do salário de homens brancos em funções equivalentes — disparidade que não pode ser explicada pela competência individual, mas pela sobreposição estrutural de sexismo e racismo.",
    tags: ["desigualdade salarial", "gênero", "raça", "trabalho"],
  },
  {
    id: "r35",
    author: "DataSUS / Ministério da Saúde",
    work: "Sistema de Informações sobre Mortalidade (SIM) 2022",
    summary: "Negros representam 75% das vítimas de homicídio no Brasil e têm mortalidade materna 1,7 vezes maior que mulheres brancas. O racismo é um determinante de saúde.",
    category: "dados",
    themes: ["saude", "racismo", "desigualdade", "violencia"],
    howToUse: "Use para temas que articulam saúde e racismo, demonstrando que a cor da pele determina expectativa de vida e acesso a cuidados.",
    example: "O DataSUS (2022) registra que mulheres negras morrem 1,7 vezes mais no parto do que mulheres brancas no Brasil — dado que demonstra como o racismo estrutural opera no interior do sistema de saúde, afetando não apenas o acesso, mas a qualidade do cuidado prestado.",
    tags: ["mortalidade materna", "racismo institucional", "saúde", "desigualdade racial"],
  },
  {
    id: "r36",
    author: "Banco Mundial",
    work: "Relatório sobre Pobreza no Brasil (2022)",
    summary: "O Brasil tem 62,5 milhões de pessoas em situação de pobreza (renda inferior a R$ 497/mês). Destes, 31,6 milhões vivem em extrema pobreza. A pandemia reverteu décadas de progresso social.",
    category: "dados",
    themes: ["desigualdade", "saude", "educacao", "trabalho"],
    howToUse: "Use para embasar argumentos sobre pobreza, insegurança alimentar ou a necessidade de políticas públicas redistributivas.",
    example: "O Banco Mundial (2022) estima que 62,5 milhões de brasileiros vivem abaixo da linha de pobreza — contingente que a pandemia ampliou em décadas de retrocesso social, revelando a fragilidade de um crescimento econômico que não se converte em proteção social estrutural.",
    tags: ["pobreza", "extrema pobreza", "desigualdade", "pandemia"],
  },

  // ── LITERATURA (continuação) ──
  {
    id: "r37",
    author: "Graciliano Ramos",
    work: "Vidas Secas (1938)",
    summary: "Romance que retrata a miséria e a desumanização de uma família de retirantes nordestinos. Fabiano, Sinhá Vitória e os dois filhos sem nome simbolizam a exclusão social histórica do sertanejo.",
    category: "literatura",
    themes: ["desigualdade", "trabalho", "educacao"],
    howToUse: "Use para temas sobre desigualdade regional, pobreza, migração forçada ou qualquer discussão sobre exclusão social no Brasil. Literatura nacional valoriza o conhecimento da cultura brasileira.",
    example: "Em 'Vidas Secas', Graciliano Ramos demonstra que a pobreza não é apenas ausência de renda — é desumanização sistemática: os filhos de Fabiano não têm sequer nome, evidenciando como a exclusão histórica do nordestino o reduz a dado estatístico, não a sujeito de direitos.",
    tags: ["nordeste", "seca", "pobreza", "exclusão social"],
  },
  {
    id: "r38",
    author: "Carolina Maria de Jesus",
    work: "Quarto de Despejo (1960)",
    summary: "Diário de catadora negra e moradora de favela em São Paulo, que registrou em cadernos encontrados no lixo a fome, a violência e a invisibilidade dos pobres. Tornou-se símbolo de resistência literária.",
    category: "literatura",
    themes: ["desigualdade", "racismo", "genero", "violencia"],
    howToUse: "Use para temas sobre pobreza urbana, racismo, invisibilidade social ou valorização de vozes periféricas. A citação direta de uma mulher negra periférica tem enorme impacto.",
    example: "Carolina Maria de Jesus, em 'Quarto de Despejo', desnuda com brutal precisão a fome estrutural do Brasil urbano: sua voz de catadora negra e favelada, escrita em cadernos salvos do lixo, permanece como acusação viva à invisibilidade imposta às populações periféricas.",
    tags: ["favela", "fome", "mulher negra", "literatura periférica"],
  },
  {
    id: "r39",
    author: "Machado de Assis",
    work: "O Alienista (1882) / Memórias Póstumas de Brás Cubas (1881)",
    summary: "Machado satiriza instituições e a sociedade brasileira do século XIX, denunciando hipocrisia, egoísmo das elites e a normalização da escravidão. É considerado o maior escritor brasileiro.",
    category: "literatura",
    themes: ["desigualdade", "democracia", "saude", "cultura"],
    howToUse: "Use para temas sobre medicalização, poder institucional, hipocrisia social ou qualquer discussão que demande perspectiva crítica sobre a sociedade brasileira.",
    example: "Machado de Assis, em 'O Alienista', satiriza a patologização do diferente: o doutor Simão Bacamarte interna toda a cidade como louca, até restar apenas ele. A sátira permanece atual diante de diagnósticos psiquiátricos que marginalizam o não-conformismo social.",
    tags: ["crítica social", "loucura", "poder médico", "sátira"],
  },
  {
    id: "r40",
    author: "Aldous Huxley",
    work: "Admirável Mundo Novo (1932)",
    summary: "Distopia em que o controle social é exercido não pela força, mas pelo prazer: condicionamento, drogas (soma) e entretenimento constante criam cidadãos felizes e conformados que nunca questionam o sistema.",
    category: "literatura",
    themes: ["tecnologia", "democracia", "saude", "cultura"],
    howToUse: "Use para temas sobre controle social pelo entretenimento, vício em redes sociais, medicalização ou qualquer contexto em que o prazer imediato substitui o pensamento crítico.",
    example: "Aldous Huxley, em 'Admirável Mundo Novo', previu um totalitarismo mais eficiente que o de Orwell: não a censura pela força, mas a anestesia pelo prazer. O vício em redes sociais e o consumo compulsivo de conteúdo reproduzem essa lógica com surpreendente fidelidade.",
    tags: ["distopia", "controle pelo prazer", "conformismo", "entretenimento"],
  },
  {
    id: "r41",
    author: "Yuval Noah Harari",
    work: "Sapiens: Uma Breve História da Humanidade (2011) / Homo Deus (2015)",
    summary: "Harari analisa como mitos e ficções coletivas (dinheiro, nações, religião) permitiram a cooperação humana em larga escala, e projeta como a biotecnologia e a IA podem redesenhar a humanidade.",
    category: "literatura",
    themes: ["tecnologia", "democracia", "desigualdade"],
    howToUse: "Use para temas sobre tecnologia, inteligência artificial, futuro do trabalho ou qualquer discussão sobre as transformações trazidas pelo avanço científico.",
    example: "Yuval Noah Harari, em 'Homo Deus', alerta que a próxima grande divisão social não será entre ricos e pobres, mas entre aqueles com acesso a melhorias biotecnológicas e os excluídos desse processo — desigualdade que pode tornar obsoleta qualquer agenda de justiça social atual.",
    tags: ["IA", "biotecnologia", "futuro", "desigualdade tecnológica"],
  },
  {
    id: "r42",
    author: "Sérgio Buarque de Holanda",
    work: "Raízes do Brasil (1936)",
    summary: "Holanda analisa o 'homem cordial' brasileiro — não bondoso, mas dominado por relações pessoais e afetivas que subvertem o espaço público, gerando nepotismo, patrimonialismo e dificuldade de separar público e privado.",
    category: "literatura",
    themes: ["democracia", "cultura", "desigualdade", "trabalho"],
    howToUse: "Use para temas sobre corrupção, patrimonialismo, nepotismo ou qualquer discussão sobre a cultura política brasileira e a dificuldade de consolidar instituições impessoais.",
    example: "Sérgio Buarque de Holanda, ao cunhar o conceito de 'homem cordial' em 'Raízes do Brasil', diagnosticou o mal-estar político nacional: a prevalência das relações pessoais sobre as institucionais gera o patrimonialismo que compromete a eficácia do Estado e a isonomia democrática.",
    tags: ["homem cordial", "patrimonialismo", "cultura política", "Brasil"],
  },

  // ── HISTÓRIA (continuação) ──
  {
    id: "r43",
    author: "Abolição da Escravidão no Brasil",
    work: "Lei Áurea — Lei 3.353/1888",
    summary: "O Brasil foi o último país do Ocidente a abolir a escravidão, em 1888. A abolição ocorreu sem qualquer política de reparação, inserção econômica ou social dos libertos, lançando 4 milhões de pessoas à margem da sociedade.",
    category: "historia",
    themes: ["racismo", "desigualdade", "trabalho", "democracia"],
    howToUse: "Use para fundamentar argumentos sobre racismo estrutural, desigualdade racial persistente e a necessidade de políticas afirmativas como reparação histórica.",
    example: "A abolição da escravidão no Brasil (1888), a mais tardia do Ocidente, não foi acompanhada de qualquer política de inserção social dos libertos — omissão que explica por que, mais de um século depois, negros ainda representam 75% dos mais pobres e das vítimas de homicídio no país.",
    tags: ["escravidão", "Lei Áurea", "abolição", "reparação histórica"],
  },
  {
    id: "r44",
    author: "Ditadura Militar Brasileira",
    work: "Período 1964-1985 / Relatório da Comissão Nacional da Verdade (2014)",
    summary: "O regime militar brasileiro (1964-1985) reprimiu, torturou e assassinou opositores. A Comissão Nacional da Verdade (2014) documentou 434 mortes e desaparecimentos e 8.350 casos de tortura.",
    category: "historia",
    themes: ["democracia", "violencia", "educacao"],
    howToUse: "Use para temas sobre democracia, liberdade de expressão, memória histórica ou qualquer discussão sobre os riscos do autoritarismo.",
    example: "A Comissão Nacional da Verdade (2014) documentou que a Ditadura Militar brasileira (1964-1985) praticou tortura sistematicamente e eliminou fisicamente opositores — herança que a democracia ainda não processou integralmente e que alimenta movimentos de reabilitação do período.",
    tags: ["ditadura", "tortura", "democracia", "memória"],
  },
  {
    id: "r45",
    author: "Conferência Rio-92 / Cúpula da Terra",
    work: "Agenda 21 e Declaração do Rio (1992)",
    summary: "A Conferência das Nações Unidas sobre Meio Ambiente e Desenvolvimento (Rio-92) reuniu 178 países e produziu a Agenda 21 e os Princípios de Desenvolvimento Sustentável, marco fundador da agenda ambiental global.",
    category: "historia",
    themes: ["meio-ambiente", "democracia"],
    howToUse: "Use para temas ambientais que demandem perspectiva histórica sobre comprometimentos internacionais e a distância entre acordos globais e ações nacionais.",
    example: "Trinta anos após a Rio-92, em que o Brasil assumiu compromissos de desenvolvimento sustentável perante 178 nações, os dados do INPE mostram que o desmatamento da Amazônia atingiu níveis recordes — evidência de que acordos internacionais sem mecanismos coercitivos têm eficácia limitada.",
    tags: ["Rio-92", "desenvolvimento sustentável", "Agenda 21", "compromissos climáticos"],
  },
  {
    id: "r46",
    author: "Tragédia de Mariana / Rompimento da Barragem de Fundão",
    work: "Rompimento da barragem da Samarco (2015)",
    summary: "O rompimento da barragem de Fundão, em Mariana (MG), em 2015, liberou 40 milhões de m³ de rejeitos de mineração, matou 19 pessoas e destruiu o Rio Doce em 663 km — o maior desastre ambiental da história brasileira.",
    category: "historia",
    themes: ["meio-ambiente", "democracia", "desigualdade"],
    howToUse: "Caso emblemático para temas sobre responsabilidade corporativa, fiscalização ambiental, justiça climática ou impunidade de grandes empresas.",
    example: "O rompimento da barragem de Fundão (Mariana, 2015) — o maior desastre ambiental da história brasileira — demonstra que a ausência de fiscalização rigorosa transfere para a sociedade os custos do lucro privado, atingindo desproporcionalmente comunidades ribeirinhas e populações tradicionais.",
    tags: ["Mariana", "mineração", "desastre ambiental", "Rio Doce"],
  },
  {
    id: "r47",
    author: "Pandemia de COVID-19",
    work: "OMS declara pandemia — março de 2020",
    summary: "A pandemia matou mais de 700 mil brasileiros, expôs fragilidades do SUS, aprofundou desigualdades e acelerou transformações digitais. O Brasil foi o 2º país em mortes absolutas no pico da pandemia.",
    category: "historia",
    themes: ["saude", "desigualdade", "tecnologia", "trabalho"],
    howToUse: "Use para temas sobre saúde pública, desigualdade social, trabalho remoto ou qualquer contexto que a pandemia ilustre com clareza.",
    example: "A pandemia de COVID-19 revelou com brutalidade as hierarquias de morte no Brasil: enquanto trabalhadores formais fizeram home-office, trabalhadores informais — majoritariamente negros e pobres — continuaram expostos sem proteção, evidenciando que a doença atinge a todos, mas mata de forma seletiva.",
    tags: ["pandemia", "COVID", "SUS", "desigualdade"],
  },
  {
    id: "r48",
    author: "Apartheid na África do Sul",
    work: "Sistema de segregação racial (1948-1994)",
    summary: "O apartheid foi um sistema institucionalizado de segregação racial na África do Sul, desmantelado em 1994 com as primeiras eleições multirraciais e a eleição de Nelson Mandela. Demonstra que o racismo estrutural pode ser superado com vontade política.",
    category: "historia",
    themes: ["racismo", "democracia", "violencia"],
    howToUse: "Use para temas sobre racismo estrutural, políticas reparatórias ou transição democrática. Mandela é referência universal de resistência não-violenta.",
    example: "O fim do apartheid sul-africano demonstra que sistemas de segregação racial institucionalizados podem ser desmantelados — mas também que a reconciliação formal não elimina desigualdades econômicas: décadas depois, a África do Sul continua entre os países mais desiguais do mundo.",
    tags: ["apartheid", "Mandela", "segregação racial", "África do Sul"],
  },

  // ── CIÊNCIA ──
  {
    id: "r19",
    author: "IPCC — Painel Intergovernamental sobre Mudanças Climáticas",
    work: "Relatório AR6 (2022)",
    summary: "O IPCC confirma que as mudanças climáticas são inequivocamente causadas pela ação humana. O aquecimento já atingiu 1,1°C acima do nível pré-industrial, com risco de ultrapassar 1,5°C até 2040.",
    category: "ciencia",
    themes: ["meio-ambiente", "desigualdade", "democracia"],
    howToUse: "Autoridade científica máxima para temas ambientais. Use para argumentar sobre urgência climática, desastres naturais, justiça ambiental ou políticas de sustentabilidade.",
    example: "O Painel Intergovernamental sobre Mudanças Climáticas (IPCC, 2022) confirma que o aquecimento global já atingiu 1,1°C acima dos níveis pré-industriais, ameaçando desproporcionalmente populações vulneráveis — o que caracteriza a crise climática também como uma questão de justiça social.",
    tags: ["aquecimento global", "clima", "carbono", "sustentabilidade"],
  },
  {
    id: "r20",
    author: "INPE — Instituto Nacional de Pesquisas Espaciais",
    work: "Monitoramento do Desmatamento na Amazônia (2023)",
    summary: "O Brasil perdeu 11.568 km² de floresta amazônica em 2022 — área equivalente a 10 vezes o município de São Paulo. A Amazônia já perdeu 20% de sua cobertura original.",
    category: "ciencia",
    themes: ["meio-ambiente", "democracia"],
    howToUse: "Dado nacional concreto para temas ambientais. O INPE é a fonte oficial de dados sobre desmatamento, o que confere alta credibilidade ao argumento.",
    example: "Segundo dados do INPE (2023), o Brasil desmatou 11.568 km² da Amazônia em 2022 — área equivalente a dez municípios de São Paulo —, evidenciando que a destruição da maior floresta tropical do planeta avança em ritmo incompatível com os compromissos climáticos internacionais assumidos pelo governo brasileiro.",
    tags: ["desmatamento", "Amazônia", "floresta", "biodiversidade"],
  },

  // ── CIÊNCIA (continuação) ──
  {
    id: "r52",
    author: "Charles Darwin",
    work: "A Origem das Espécies (1859)",
    summary: "Darwin estabeleceu a teoria da evolução por seleção natural — consenso científico há 160 anos. Revolucionou a biologia e fornece base para compreender diversidade humana sem hierarquias.",
    category: "ciencia",
    themes: ["educacao", "cultura", "democracia"],
    howToUse: "Use para temas sobre negacionismo, ensino de ciências ou tensão entre saber científico e crenças religiosas no espaço público.",
    example: "A tentativa de incluir criacionismo nos currículos escolares ignora que a evolução darwiniana é consenso científico há 160 anos — confundir teoria científica com crença religiosa compromete a formação crítica e o desenvolvimento científico do país.",
    tags: ["evolução", "seleção natural", "negacionismo", "ciência"],
  },
  {
    id: "r53",
    author: "Sigmund Freud",
    work: "O Mal-Estar na Civilização (1930)",
    summary: "Freud argumenta que a civilização exige repressão dos instintos individuais, gerando inevitável mal-estar psíquico. A tensão entre pulsões e normas sociais é fonte permanente de sofrimento.",
    category: "ciencia",
    themes: ["saude", "cultura", "violencia"],
    howToUse: "Use para temas sobre saúde mental, violência coletiva ou tensão entre desejos individuais e normas sociais.",
    example: "Freud, em 'O Mal-Estar na Civilização', identificou que a vida em sociedade exige renúncia pulsional — análise que ressoa na epidemia de ansiedade contemporânea: quanto mais a cultura exige desempenho e conformidade, maior o custo psíquico individual.",
    tags: ["psicanálise", "mal-estar", "repressão", "saúde mental"],
  },
  {
    id: "r54",
    author: "INPA — Instituto Nacional de Pesquisas da Amazônia",
    work: "Ponto de não retorno da Amazônia (2021)",
    summary: "Pesquisadores estimam que a Amazônia pode atingir seu 'ponto de não retorno' entre 20-25% de desmatamento, convertendo-se de sumidouro em emissor de carbono com consequências climáticas irreversíveis.",
    category: "ciencia",
    themes: ["meio-ambiente", "democracia"],
    howToUse: "Use para argumentar urgência ambiental. O ponto de não retorno torna a inação inaceitável — argumento poderoso em C5.",
    example: "O INPA alerta que a Amazônia pode atingir um ponto de não retorno entre 20 e 25% de desmatamento, transformando-se de reguladora em emissora de carbono — processo irreversível que tornaria o Brasil epicentro da catástrofe climática global.",
    tags: ["ponto de não retorno", "Amazônia", "carbono", "clima"],
  },

  // ── LEGISLAÇÃO ──
  {
    id: "r55",
    author: "Constituição Federal do Brasil",
    work: "Constituição Federal de 1988 — 'Constituição Cidadã'",
    summary: "A Constituição de 1988 é o marco fundador da democracia brasileira. Garante dignidade humana, direitos sociais (saúde, educação, moradia), igualdade racial e liberdade de expressão como direitos fundamentais.",
    category: "legislacao",
    themes: ["democracia", "educacao", "saude", "racismo", "genero", "violencia"],
    howToUse: "Use como fundamento jurídico para qualquer argumento sobre direitos não efetivados. A distância entre o texto constitucional e a realidade é poderoso argumento.",
    example: "A Constituição Federal de 1988 garante acesso universal à educação e à saúde como direitos fundamentais — princípios sistematicamente violados por um sistema que concentra investimentos em regiões ricas, evidenciando que a democracia formal não assegura democracia real.",
    tags: ["direitos fundamentais", "dignidade humana", "Constituição", "democracia"],
  },
  {
    id: "r56",
    author: "ECA — Estatuto da Criança e do Adolescente",
    work: "Lei 8.069/1990",
    summary: "O ECA reconhece crianças e adolescentes como sujeitos de direitos plenos, com proteção integral do Estado, família e sociedade. É referência legislativa internacional na proteção da infância.",
    category: "legislacao",
    themes: ["violencia", "educacao", "desigualdade", "democracia"],
    howToUse: "Use para temas sobre exploração infantil, violência doméstica, trabalho infantil ou qualquer discussão sobre direitos de crianças.",
    example: "O ECA (Lei 8.069/1990), reconhecido internacionalmente como modelo de proteção à infância, é sistematicamente desrespeitado no Brasil: trabalho infantil ainda atinge 1,8 milhão de crianças, revelando que legislação protetiva, sem fiscalização e políticas sociais, não se efetiva.",
    tags: ["ECA", "criança", "adolescente", "proteção integral"],
  },
  {
    id: "r57",
    author: "LGPD — Lei Geral de Proteção de Dados",
    work: "Lei 13.709/2018",
    summary: "A LGPD regulamenta o tratamento de dados pessoais no Brasil, inspirada na GDPR europeia. Estabelece bases legais para coleta, direitos dos titulares e obrigações de empresas e governo.",
    category: "legislacao",
    themes: ["tecnologia", "democracia"],
    howToUse: "Use para temas sobre privacidade digital, vigilância ou proteção de dados pessoais. Demonstra que o Brasil avançou legislativamente mas ainda enfrenta desafios de implementação.",
    example: "A LGPD (2018) representa um avanço na proteção de dados pessoais no Brasil, mas sua efetividade ainda é limitada: a ANPD — autoridade responsável pela fiscalização — opera com recursos insuficientes, tornando a lei mais simbólica do que coercitiva perante as grandes plataformas.",
    tags: ["LGPD", "proteção de dados", "privacidade", "tecnologia"],
  },
  {
    id: "r58",
    author: "Marco Civil da Internet",
    work: "Lei 12.965/2014",
    summary: "O Marco Civil estabelece princípios, garantias e deveres para o uso da internet no Brasil: neutralidade de rede, privacidade, liberdade de expressão e responsabilidade dos provedores.",
    category: "legislacao",
    themes: ["tecnologia", "democracia"],
    howToUse: "Use para temas sobre regulação digital, liberdade de expressão online, responsabilidade de plataformas ou desinformação.",
    example: "O Marco Civil da Internet (2014), pioneiro na regulação digital, já mostrava que a internet não pode ser espaço sem lei — mas sua insuficiência diante das fake news e da manipulação algorítmica evidencia a necessidade de atualização constante do arcabouço regulatório.",
    tags: ["Marco Civil", "internet", "neutralidade de rede", "liberdade"],
  },
  {
    id: "r59",
    author: "Lei de Cotas",
    work: "Lei 12.711/2012",
    summary: "A Lei de Cotas reserva 50% das vagas federais para estudantes de escolas públicas e determina a reserva de vagas por autodeclaração racial, aumentando a presença de negros e indígenas no ensino superior.",
    category: "legislacao",
    themes: ["racismo", "educacao", "desigualdade"],
    howToUse: "Use para defender ações afirmativas com base legal, ou para discutir a tensão entre igualdade formal e igualdade material.",
    example: "A Lei de Cotas (2012), ao reservar vagas raciais no ensino superior federal, baseou-se no princípio de que igualdade real exige tratamento desigual — pois tratar igualmente sujeitos historicamente desigualizados é manutenção do privilégio, não justiça.",
    tags: ["cotas raciais", "ação afirmativa", "ensino superior", "equidade"],
  },
  {
    id: "r60",
    author: "Declaração Universal dos Direitos Humanos",
    work: "ONU — 1948",
    summary: "Documento fundador do direito internacional dos direitos humanos, proclamado após o Holocausto. Reconhece dignidade inalienável de todo ser humano independente de raça, sexo, língua, religião ou origem.",
    category: "legislacao",
    themes: ["democracia", "violencia", "racismo", "genero", "desigualdade"],
    howToUse: "Use como fundamento universal para qualquer argumento sobre direitos humanos — especialmente em C5, para validar que a proposta respeita a dignidade.",
    example: "A Declaração Universal dos Direitos Humanos (ONU, 1948) estabelece que toda pessoa tem direito à educação, saúde e segurança — princípios que o Estado brasileiro viola sistematicamente ao concentrar investimentos nas regiões mais ricas e deixar populações periféricas sem acesso a serviços básicos.",
    tags: ["direitos humanos", "ONU", "dignidade", "universalidade"],
  },
  {
    id: "r61",
    author: "Convenção 169 da OIT",
    work: "Organização Internacional do Trabalho — 1989",
    summary: "A Convenção 169 garante direitos de consulta e consentimento livre, prévio e informado a povos indígenas e tribais sobre decisões que afetem seus territórios e modos de vida.",
    category: "legislacao",
    themes: ["racismo", "democracia", "meio-ambiente"],
    howToUse: "Use para temas sobre direitos indígenas, demarcação de terras ou grandes obras em territórios tradicionais.",
    example: "A Convenção 169 da OIT, ratificada pelo Brasil em 2002, exige consulta prévia, livre e informada aos povos indígenas sobre projetos que afetem seus territórios — direito sistematicamente desrespeitado em obras de hidrelétricas, mineração e expansão do agronegócio.",
    tags: ["povos indígenas", "consulta prévia", "OIT", "territórios"],
  },
  {
    id: "r62",
    author: "Estatuto da Igualdade Racial",
    work: "Lei 12.288/2010",
    summary: "O Estatuto define como crime o racismo e estabelece políticas de promoção da igualdade racial no Brasil, reconhecendo a discriminação histórica sofrida pela população negra.",
    category: "legislacao",
    themes: ["racismo", "desigualdade", "democracia"],
    howToUse: "Use para temas sobre racismo estrutural, demonstrando que apesar do arcabouço legal, a discriminação persiste — criando tensão entre norma e realidade.",
    example: "O Estatuto da Igualdade Racial (2010) reconhece formalmente que a população negra foi historicamente discriminada e determina políticas reparatórias — mas os dados do IBGE mostram que negros ainda ganham 40% menos que brancos, evidenciando que lei sem implementação é letra morta.",
    tags: ["igualdade racial", "discriminação", "política racial", "reparação"],
  },

  // ── ARTE E CULTURA ──
  {
    id: "r63",
    author: "Caetano Veloso / Tropicalismo",
    work: "Movimento Tropicalista (1967-1968)",
    summary: "O Tropicalismo foi movimento cultural que misturou rock, bossa nova, vanguarda e referências populares para criticar a ditadura militar e o conservadorismo cultural brasileiro.",
    category: "arte",
    themes: ["cultura", "democracia", "violencia"],
    howToUse: "Use para temas sobre censura, liberdade de expressão ou o papel da arte na resistência política.",
    example: "O Tropicalismo, ao misturar estéticas contraditórias numa época de censura, demonstrou que a arte pode ser resistência política sem panfleto: a subversão formal foi a mensagem — lição que permanece atual quando governos tentam controlar a produção cultural.",
    tags: ["Tropicalismo", "ditadura", "censura", "resistência cultural"],
  },
  {
    id: "r64",
    author: "Cinema Novo Brasileiro",
    work: "Glauber Rocha — Terra em Transe (1967) / Deus e o Diabo na Terra do Sol (1964)",
    summary: "O Cinema Novo expôs a miséria, o coronelismo e a alienação política do povo brasileiro com estética crua e comprometimento social, tornando-se referência mundial de cinema político.",
    category: "arte",
    themes: ["desigualdade", "cultura", "democracia"],
    howToUse: "Use para temas sobre representação da pobreza, papel político da arte ou desigualdade regional.",
    example: "Glauber Rocha, em 'Deus e o Diabo na Terra do Sol', captou a tragédia do nordestino entre o fanatismo religioso e o banditismo como formas desesperadas de escapar da miséria estrutural — um retrato que a realidade social de décadas depois ainda não desmentiu.",
    tags: ["Cinema Novo", "nordeste", "pobreza", "cinema político"],
  },
  {
    id: "r65",
    author: "Indústria Cultural",
    work: "Theodor Adorno e Max Horkheimer — Dialética do Esclarecimento (1944)",
    summary: "Adorno e Horkheimer cunharam 'indústria cultural' para descrever a padronização do entretenimento de massa que transforma cultura em mercadoria, domestica o pensamento crítico e mantém as massas conformadas.",
    category: "arte",
    themes: ["cultura", "tecnologia", "democracia"],
    howToUse: "Use para temas sobre cultura de massa, streaming, redes sociais ou qualquer discussão sobre como o entretenimento pode ser instrumento de controle social.",
    example: "O conceito de 'indústria cultural', cunhado por Adorno e Horkheimer em 1944, antecipou o modelo dos algoritmos de recomendação: ao oferecer sempre o que o usuário já gosta, as plataformas eliminam o atrito necessário para o crescimento crítico.",
    tags: ["indústria cultural", "entretenimento", "conformismo", "mídia de massa"],
  },
  {
    id: "r66",
    author: "Frantz Fanon / Négritude",
    work: "Aimé Césaire — Discurso sobre o Colonialismo (1950)",
    summary: "O movimento Négritude, liderado por Césaire, revalorizou a cultura africana e negra como resposta à desumanização colonial, afirmando identidade e orgulho negro como ato político.",
    category: "arte",
    themes: ["racismo", "cultura", "educacao"],
    howToUse: "Use para temas sobre identidade negra, valorização cultural ou resistência ao apagamento histórico.",
    example: "O movimento Négritude, ao reivindicar a beleza e o valor da cultura africana diante do eurocentrismo colonial, demonstrou que a afirmação identitária é ato político: o orgulho cultural é também resistência à narrativa que hierarquiza humanidades.",
    tags: ["Négritude", "identidade negra", "colonialismo", "resistência"],
  },
  {
    id: "r67",
    author: "Walter Benjamin",
    work: "A Obra de Arte na Era de sua Reprodutibilidade Técnica (1935)",
    summary: "Benjamin analisa como a reprodução técnica (fotografia, cinema) destrói a 'aura' da obra de arte — sua autenticidade única — e transforma a percepção estética, democratizando o acesso mas também instrumentalizando a arte.",
    category: "arte",
    themes: ["tecnologia", "cultura", "democracia"],
    howToUse: "Use para temas sobre tecnologia e cultura, democratização do acesso à arte ou o impacto digital na autenticidade.",
    example: "Walter Benjamin antecipou que a reprodutibilidade técnica transformaria a relação com a arte — análise que a era digital radicalizou: quando qualquer imagem pode ser copiada e circulada infinitamente, a distinção entre original e cópia, autêntico e falso, torna-se politicamente relevante.",
    tags: ["aura", "reprodutibilidade", "arte", "tecnologia"],
  },
];

export const repertoireThemes: Record<RepertoireTheme, string> = {
  tecnologia: "Tecnologia e Sociedade",
  desigualdade: "Desigualdade Social",
  educacao: "Educação",
  saude: "Saúde",
  "meio-ambiente": "Meio Ambiente",
  democracia: "Democracia e Política",
  genero: "Gênero e Feminismo",
  racismo: "Racismo e Diversidade",
  violencia: "Violência",
  trabalho: "Trabalho e Economia",
  cultura: "Cultura e Arte",
};

export const repertoireCategories: Record<RepertoireCategory, string> = {
  filosofia: "Filosofia",
  dados: "Dados e Estatísticas",
  literatura: "Literatura e Obras",
  historia: "História e Eventos",
  ciencia: "Ciência",
  arte: "Arte e Cultura",
  legislacao: "Legislação",
};
